### ISSUE TITLE
Failed to download 

### ISSUE THREAD

**Issue by Sunekaer** [brandon3055/ProjectIntelligence#1]
## Base information
* Minecraft version:1.12.2
* Mod version:Draconic-Evolution-1.12.2-2.3.18.329-universal
* Minecraft Forge version: 2796
* Mod Pack: (if applicable) FTB-Presents-Stoneblock-2

* **Issue**: Draconic Evolution Information Tablet opens blank with an error trying to download info from a web address
![2019-01-10_19 15 12](https://user-images.githubusercontent.com/36059797/50965533-2a4da300-150d-11e9-9a80-26e1768fd22f.png)

https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/issues/84

**Comment by FuseSpark2** [comment]
I'm having the same issue is there a current fix to this?

**Comment by brandon3055** [comment]
The latest version should correctly follow redirects. But in any case please test with this version of PI
http://chickenbones.net/maven/com/brandon3055/projectintelligence/ProjectIntelligence/1.12.2-1.0.2.15/ProjectIntelligence-1.12.2-1.0.2.15-universal.jar
If you can confirm that it fixed the issue i will push a new release.

Edit: Looks like SB2 is running the latest core so i have no idea why this issue is occurring for some people. Unfortunately i am unable to reproduce the issue so i need someone who can to test that version of PI before i push it.

It may also help to know what part of the world you live in. If this issue is region specific i may be able to reproduce it with a VPN.

**Comment by Beeradise** [comment]
I am having the same issue and I live in the U.S. state of Kansas.
Thanks for your time!

**Comment by BleakChimera** [comment]
I am also having this issue. I downloaded the newest PI and it did not resolve it.

**Comment by professorcraft1** [comment]
I tried installing the JAR file and have the same issue, except now the error message references the URL with https

**Comment by FuseSpark2** [comment]
I live in Washington state and have the issue, I've tried redownloading the version and it hasn't helped still the same error message.

**Comment by BrockWS** [comment]
Can everyone confirm what Minecraft launcher & Java version (Check Java version ingame with f3) you are using. With Twitch, the Native Launcher ships with Java 8 51 which does not support Lets Encrypt certificate.

**Comment by FuseSpark2** [comment]
launcher version 2.1.146 and java is the latest version

**Comment by brandon3055** [comment]
Thanks for pointing that out @BrockWS I have now confirmed that this is the issue. I will have to get @covers1624 to help figure out a solution if there is one... In the mean time the fastest fix for anyone with this issue would be to update twitch to the latest java version.

**Comment by brandon3055** [comment]
Ok so for now you can fix this by installing the fallowing mod. 
https://minecraft.curseforge.com/projects/vanillafix?gameCategorySlug=mc-mods&projectID=292785
And I will look into adding this fix directly to PI

**Comment by BleakChimera** [comment]
Just to follow up, Vanilla Fix DOES let me access the Draconic Evo mod information (yay, I can finally start playing it for the first time!) but does still give an error about downloading mod info.

**Comment by brandon3055** [comment]
@BleakChimera Can you show me the error?

**Comment by TheInfamousAlk** [comment]
This is happening to me now, and vanillafix does not solve the issue. One difference with my issue though is that it worked previously but it does not work anymore.

**Comment by FoxMcloud5655** [comment]
It's an issue with the Russian documentation.  There's an issue open about it on Draconic Evolutions's issue tracker, if you'd like to fix it real quick before it's officially fixed.

**Comment by VTArxelus** [comment]
This issue is also happening in All The Mods 3 Remix using the Native Launcher from Twitch. VanillaFix just crashes ATM3R.

**Comment by ashton727** [comment]
Same issue, downloaded the files from the master... but things weren't loading properly. Not sure if it's an ATM3 issue or not as PI doesn't interact with anything modpack specific..

The real question is why did you opt for an internet reliant mod than just putting the documentation in for the specific mod.

**Comment by JanSeidlerSF** [comment]
Same for me on ATM3.

After decades of IT there's still developers out there who simply do not get the fact that there will ALWAYS be upcoming problems when they force people to go online when it's not needed and that any static URL will vanish sooner or later. 

https://pi.brandon3055.com/mnifest.json is simply a 404, end of story.

**Comment by Shibva** [comment]
@brandon3055 I think i found the problem
![image](https://user-images.githubusercontent.com/38770780/70364994-29c4a600-185d-11ea-9354-40a9b13d90c2.png)

there are 2 marks instead of 1

**Comment by Shibva** [comment]
ftr i downloaded those files manually though some other means
Just so you know
I hope this find helps

**Comment by VTArxelus** [comment]
> @brandon3055 I think i found the problem
> ![image](https://user-images.githubusercontent.com/38770780/70364994-29c4a600-185d-11ea-9354-40a9b13d90c2.png)
> 
> there are 2 marks instead of 1

Nice try dude. That's not the same as me.
![image](https://user-images.githubusercontent.com/53189264/70368443-1a9b2380-1870-11ea-970a-95c45232bfff.png)

**Comment by TheInfamousAlk** [comment]
The 2nd dot was just the tip of the J.

**Comment by TheInfamousAlk** [comment]
Your circle was covering the rest of the J.

**Comment by NordicGamerFE** [comment]
![image](https://user-images.githubusercontent.com/18188155/85232970-a1c27a00-b403-11ea-9ed4-b60325f3cba9.png)

BrandonsCore-1.12.2-2.4.18.210-universal.jar
--
ProjectIntelligence-1.12.2-1.0.9.28-universal.jar
--
forge-14.23.5.2854

**Comment by Shibva** [comment]
ive deemed that this is when certen other mods are present when other than those mods
some other mods seem to be conflicting wiht the download process

**Comment by FoxMcloud5655** [comment]
Providing some examples would be nice.

**Comment by Shibva** [comment]
it does this in light magic/tech modpacks

**Comment by FoxMcloud5655** [comment]
Okay, maybe I need to be a little bit more clear.

Some specific examples of mods that have been tested and known to produce this issue would be nice to see.

Giving a general direction makes it very hard to precisely determine what's causing the issue in the first place.  Mod developers don't have the time to individually check every single mod to find out which ones are compatible with their own.

**Comment by covers1624** [comment]
We need mod lists of these supposed ' light magic/ tech packs', The file exists on the server, we fixed certificate things, it follows redirects, literelly anything else is either, somw mod breaking the certificate stuff (we need logs!), Or a network issue.

**Comment by Shibva** [comment]
sorry I wish i had the time but i dont

**Comment by FoxMcloud5655** [comment]
And now you see our dilemma!  We can't fix what we can't reproduce.

**Comment by Shibva** [comment]
I could give you the list

**Comment by Shibva** [comment]
its a small one if you want I just need a little time

**Comment by Shibva** [comment]
im also using Twitch, if i forgot to menchon

**Comment by FoxMcloud5655** [comment]
That and a log dating back to when the issue occured would go far in helping to diagnose this issue.

**Comment by Shibva** [comment]
ok

**Comment by Shibva** [comment]
[latest.log](https://github.com/brandon3055/ProjectIntelligence/files/4810987/latest.log)
Keep in mind i was playing on a private server 

Hopes this helps in some way

its somewhere in this pack of mods that the issue exists

**Comment by Shibva** [comment]
its not the same but this pack also has this issue in it so it should help

**Comment by festro** [comment]
Nice to see I'm not the only one having the issue.

**Comment by SGZ-Creations** [comment]
Having this issue tho i saw i had Java 8 build 291 and I don't think they have changed the way it dose here ⬇️ 

> Can everyone confirm what Minecraft launcher & Java version (Check Java version ingame with f3) you are using. With Twitch, the Native Launcher ships with Java 8 51 which does not support Lets Encrypt certificate.

And I do have 
![image](https://user-images.githubusercontent.com/59801736/120945968-2f919500-c73b-11eb-9b62-90a261dfb36f.png)

**Comment by FoxMcloud5655** [comment]
That's Java 8 version 51.  You need to tell your launcher to use a custom version of Java.

**Comment by SGZ-Creations** [comment]
> That's Java 8 version 51. You need to tell your launcher to use a custom version of Java.

How in Curseforge/Overwolf ? Tho issue solved in #33
