### ISSUE TITLE
A lot of images not downloadable

### ISSUE THREAD

**Issue by aaronhowser1** [brandon3055/ProjectIntelligence#17]
![image](https://user-images.githubusercontent.com/15698722/67629504-b8004200-f844-11e9-8809-70c73b7db702.png)
![image](https://user-images.githubusercontent.com/15698722/67629506-c51d3100-f844-11e9-8d64-fad2bc1b856a.png)
Shift clicking does not work. This is using FTB Academy 1.1.0 (with SmoothFont removed)

**Comment by brandon3055** [comment]
Are you still getting this issue? Occasionally the image server goes down but i usually have it fixed within a few hours. If things are working now than i suspect that's all it was.

**Comment by aaronhowser1** [comment]
Yep, everything's fine now as far as I can tell.
