### ISSUE TITLE
API jar

### ISSUE THREAD

**Issue by HenryLoenwind** [brandon3055/ProjectIntelligence#2]
Please provide an API jar.

The current setup not only breaks for mods that don't use the same mappings version as you (deobf jars died with 1.7.10...), it also pulls in an extra JEI (in an older version than the one we need), an extra RedstoneFlux (wrong version and also deobf), a CodeChickenLib and a BrandonsCore.

As it is now, I'd be surprised if more than half of the mods out there could use it without breaking their build.

**Comment by brandon3055** [comment]
Ok i think i got this figured out. You can find the API jar with the latest release on curse. Let me know if you have any issues.
