### ISSUE TITLE
No Graphite bar / dust recipe?

### ISSUE THREAD

**Issue by IMNoLifeKing** [brandon3055/ProjectIntelligence#30]
I am new to modding and I wanted to use this mod in the mod pack but I can't seem to make graphite bars. Jei tells me I need graphite dust to make graphite bars and graphite bars to make graphite dust, meaning I cant make graphite, any idea how to fix?

**Comment by FoxMcloud5655** [comment]
I think you just figured this out, but graphite bars have nothing to do with Project Intelligence!
