### ISSUE TITLE
ProjectIntelligence-1.12.2-1.0.9.28-universal can't download manifest.json

### ISSUE THREAD

**Issue by SzymonNadbrzezny** [brandon3055/ProjectIntelligence#32]
Hi, as many people before I can't use PI because of manifest download error, I tried downloading LetsEncryptCraft as someone suggested it might help, ~~I don't really want to use Vanilla Tweaks as it adds some things I don't want.~~ Read it Vanilla Fix and remembered it wrong.
![image](https://user-images.githubusercontent.com/32302761/110246069-5555a500-7f66-11eb-9b08-ea207461477f.png)
[latest.log](https://github.com/brandon3055/ProjectIntelligence/files/6097444/latest.log)
Contents of GuiConfig.json
`{
  "downloadsAllowed": true,
  "tutorialDisplayed": true,
  "editMode": false,
  "etCheckFluid": true,
  "editingRepoLoc": "",
  "editorAlwaysOnTop": false,
  "editorLineWrap": false,
  "maxTabs": 16,
  "editorLAF": "",
  "screenMode": 0,
  "screenPosOverride": false,
  "screenPosX": 0,
  "screenPosY": 0,
  "userLanguage": "[MINECRAFT-LANG]",
  "homePage": "projectintelligence:",
  "searchMode": "EVERYWHERE",
  "pageLangOverrides": {},
  "modLangOverrides": {},
  "modVersionOverrides": {}

}`

**Comment by SzymonNadbrzezny** [comment]
I might add that it seems to be problem with certification? `16:52:38.077
brandonscore
PI-Update-Manager:worker-0
ThreadFileDownloader: DL Failed sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
16:52:38.079
brandonscore
PI-Update-Manager
[Pi Reported Error]: Failed to download the PI mod manifest from https://pi.brandon3055.com/manifest.json`

**Comment by FoxMcloud5655** [comment]
There are a couple of things you can do.  First, update your Java version.  Use the latest Java 8 and see if that fixes it.  For some, it does.  For others, it doesn't.

If that does not fix your issue, then we can do it the hard way.

**Comment by SzymonNadbrzezny** [comment]
I do have Java 8 , but i'm checking now Vanilla Fix
![image](https://user-images.githubusercontent.com/32302761/110246767-2c82df00-7f69-11eb-9d20-1c6ef327a6ad.png)
![image](https://user-images.githubusercontent.com/32302761/110246786-4d4b3480-7f69-11eb-89dc-806fc774794c.png)

**Comment by FoxMcloud5655** [comment]
And that's the version that you are telling Minecraft to load from?  By default, Minecraft loads its own version which happens to be 8.51 right now unless overridden in the profile settings.

**Comment by SzymonNadbrzezny** [comment]
Vanilla Fix fixed it, but you should really add some disclaimer or dependency for now.

**Comment by SzymonNadbrzezny** [comment]
> And that's the version that you are telling Minecraft to load from? By default, Minecraft loads its own version which happens to be 8.51 right now unless overridden in the profile settings.

Nope, 8.51 is loaded, I can try without Vanilla Fix and forcing 8.281 if you want

**Comment by FoxMcloud5655** [comment]
Like I said, updating Java works for some and doesn't work for others.  You're welcome to try it, but you've got it working now, so there's no real reason to.

The hard way was not VanillaFix since you didn't want to apply it, but you've shown it works for you, so that's what I'll recommend since it's easier.

**Comment by SzymonNadbrzezny** [comment]
> Like I said, updating Java works for some and doesn't work for others. You're welcome to try it, but you've got it working now, so there's no real reason to.
> 
> The hard way was not VanillaFix since you didn't want to apply it, but you've shown it works for you, so that's what I'll recommend since it's easier.

Ooh ok, I didn't want VanillaTweaks since I misremembered the name after reading some previous issues, and only after posting I re-read the one talking about VanillaFix. Thanks for help anyway :D
