### ISSUE TITLE
Garbled.

### ISSUE THREAD

**Issue by baka-gourd** [brandon3055/ProjectIntelligence#4]
Title garbled (stored in json).
Perhaps related to language format?
system:windows10 Pro 1809(17763.379)
![rfv1](https://user-images.githubusercontent.com/36119339/54473212-a61ae300-480f-11e9-96be-808109938670.png)
![rfv2](https://user-images.githubusercontent.com/36119339/54473214-aca95a80-480f-11e9-9f98-ee30b37e0493.png)

**Comment by baka-gourd** [comment]
server system：windows server 2016 datacenter 64bit (10.0 v:14393)

**Comment by brandon3055** [comment]
Sorry i forgot to respond do this issue. Im afraid i dont know that language so i have no idea what its supposed to look like.

**Comment by TartaricAcid** [comment]
@brandon3055 Let me explain it:
you use `FileReader` method read the `structure/lang/xx_xx.json` file, this method has coding problems, so garbled characters appear when reading non-ASCII characters.

Code snippet with problem: [LanguageManager.java#L125-L127](
https://github.com/brandon3055/ProjectIntelligence/blob/master/src/main/java/com/brandon3055/projectintelligence/docmanagement/LanguageManager.java#L125-L127)
Solution: [stackoverflow](https://stackoverflow.com/questions/696626/java-filereader-encoding-issue)
> The constructors of `FileReader` always use the platform default encoding which is generally a bad idea.
> Instead of `FileReader` you need to use `new InputStreamReader(new FileInputStream(pathToFile), <encoding>)`.

**Comment by brandon3055** [comment]
Ahh ok that makes sense now. I actually had a similar issue with the markdown file where it would work fine on my Linux system but on windows it broke the select character "§"
At the time I didnt think to apply that fix to the lang file.

**Comment by brandon3055** [comment]
Ok i think i have fixed it. But can you confirm before i push a new build to curse?
http://chickenbones.net/maven/com/brandon3055/projectintelligence/ProjectIntelligence/1.12.2-1.0.5.18/

**Comment by TartaricAcid** [comment]
Thank you very much, I confirmed it again and no problem now.
