### ISSUE TITLE
PI doesn't detect Draconic Additions

### ISSUE THREAD

**Issue by FoxMcloud5655** [brandon3055/ProjectIntelligence#9]
I don't know if this is a problem with how I'm publishing my documentation or if it's an inherent bug within Project Intelligence, but Draconic Additions is not showing up inside of the docs, even though it's installed.

When in Edit Mode, it shows up just fine (since it forces all documentation to display, regardless of if the appropriate mod is installed or not) and all assets are able to be used.

**Comment by FoxMcloud5655** [comment]
Still having issues with this.  Not sure how to fix it.

**Comment by brandon3055** [comment]
your "actual" mod version is set to 1.0
https://github.com/FoxMcloud5655/Draconic-Additions/blob/master/src/main/java/net/foxmcloud/draconicadditions/DraconicAdditions.java#L26
Your documentation is targeting 1.5+
Sorry it took me so long to respond to this.

**Comment by FoxMcloud5655** [comment]
I had no idea the version number inside the main file was used for anything...  Thanks for the help!

**Comment by brandon3055** [comment]
Yea thats the version that all other mods see.
